/*
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.futebolcard.api.v1.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sensedia.futebolcard.api.v1.model.Seat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Row
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-26T09:34:10.919-03:00")
public class Row {
  @SerializedName("rowId")
  private String rowId = null;

  @SerializedName("rowAlias")
  private String rowAlias = null;

  @SerializedName("rowName")
  private String rowName = null;

  @SerializedName("seats")
  private List<Seat> seats = null;

  public Row rowId(String rowId) {
    this.rowId = rowId;
    return this;
  }

   /**
   * Get rowId
   * @return rowId
  **/
  @ApiModelProperty(example = "831411", value = "")
  public String getRowId() {
    return rowId;
  }

  public void setRowId(String rowId) {
    this.rowId = rowId;
  }

  public Row rowAlias(String rowAlias) {
    this.rowAlias = rowAlias;
    return this;
  }

   /**
   * Get rowAlias
   * @return rowAlias
  **/
  @ApiModelProperty(example = "SETORC-R", value = "")
  public String getRowAlias() {
    return rowAlias;
  }

  public void setRowAlias(String rowAlias) {
    this.rowAlias = rowAlias;
  }

  public Row rowName(String rowName) {
    this.rowName = rowName;
    return this;
  }

   /**
   * Get rowName
   * @return rowName
  **/
  @ApiModelProperty(example = "R", value = "")
  public String getRowName() {
    return rowName;
  }

  public void setRowName(String rowName) {
    this.rowName = rowName;
  }

  public Row seats(List<Seat> seats) {
    this.seats = seats;
    return this;
  }

  public Row addSeatsItem(Seat seatsItem) {
    if (this.seats == null) {
      this.seats = new ArrayList<Seat>();
    }
    this.seats.add(seatsItem);
    return this;
  }

   /**
   * Get seats
   * @return seats
  **/
  @ApiModelProperty(value = "")
  public List<Seat> getSeats() {
    return seats;
  }

  public void setSeats(List<Seat> seats) {
    this.seats = seats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Row row = (Row) o;
    return Objects.equals(this.rowId, row.rowId) &&
        Objects.equals(this.rowAlias, row.rowAlias) &&
        Objects.equals(this.rowName, row.rowName) &&
        Objects.equals(this.seats, row.seats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowId, rowAlias, rowName, seats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Row {\n");
    
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    rowAlias: ").append(toIndentedString(rowAlias)).append("\n");
    sb.append("    rowName: ").append(toIndentedString(rowName)).append("\n");
    sb.append("    seats: ").append(toIndentedString(seats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

